### ISSUE TITLE
How to generate 3D model from the output of refine segmentations

### ISSUE THREAD

**Issue by ajithvcoder** [yi-ming-qian/interplane#3]
Hi @qymwill @yi-ming-qian 

I have got results from this command from nvlabs/planercnn repo
```python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images```

![snap_results](https://user-images.githubusercontent.com/8075112/97103020-1e29da00-16d0-11eb-8163-f12e23eaaeba.PNG)

How should i use it to generate 3D mesh ?

https://github.com/NVlabs/planercnn/issues/53 . I know this is not correct place to create issue but i didnt get reply from anyone who has worked in it previously that y i have created issue here. Do you know any method with above outputs to generate 3dmesh output .ply file which is like in paper

**Comment by yi-ming-qian** [comment]
you shall write the mesh files by yourself, which can be done in just one day. I typically use .obj for mesh, which is simpler compared to .ply

Here is the specs of a .obj file: https://en.wikipedia.org/wiki/Wavefront_.obj_file. You write vertex positions and faces, then you are done.

**Comment by ajithvcoder** [comment]
@yi-ming-qian  thanks for the reply

**Comment by ajithvcoder** [comment]
@yi-ming-qian  i tried for several days not able to make it when you are free could u please make a file. At max i am able to make for a single channel and its also not good

**Comment by yi-ming-qian** [comment]
I am sorry that I am extremely busy these days. I wonder how urgent this
is.
The whole process should be simple. You have plane masks, you extract
boundaries pixels. then you perform delaunay triangulation using some
exciting packages. Then you have nodes and edges, write them into obj file,
then you are done...
