### ISSUE TITLE
Ground-truth plane segmentation annotation in Section 5.2

### ISSUE THREAD

**Issue by weiyithu** [yi-ming-qian/interplane#5]
Thanks for your great work ! In Section 5.2, you say the segmentation labels in PLaneRCNN have large errors and you annotate ground-truth by LabelMe tool. Could you provide the annotated plane segmentation labels ?

**Comment by yi-ming-qian** [comment]
Hi, I looked into my LabelMe account, [here](https://www.dropbox.com/s/z40trswz1szk3y5/collection.zip?dl=0) is what I found. Please unzip it after downloading. The Annotations folder lists the raw XML files generated by LabelMe. Please note that NOT all images have an annotation (if an XML file is about 217-219 bytes, it means I didn't label it). You need to write a script to parse the XML file. I remember I also manually combined some isolated masks if XML parsing gave me an undesired mask.

If I am remembering correctly, this is something that we did around two days before the submission deadline, so we only annotated very few samples, just for an illustration purpose.

**Comment by weiyithu** [comment]
OK. Thank you very much !
