### ISSUE TITLE
Ground-truth plane segmentation from LabelMe release

### ISSUE THREAD

**Issue by jcliu0428** [yi-ming-qian/interplane#8]
Hi Thanks for your work!

I notice in a previous [issue](https://github.com/yi-ming-qian/interplane/issues/5) you mentioned that you manually combine some of the isolated masks to further improve the gt mask quality. Could you please release the updated gt annotation files?

**Comment by yi-ming-qian** [comment]
Please see my reply here:

https://github.com/yi-ming-qian/interplane/issues/5#issuecomment-752029959

**Comment by jcliu0428** [comment]
Yes I have noticed this. So the xml files you released here is already the one you finally use(after manually combined if the labelMe annotation is not desired) to evaluate in this paper?

**Comment by yi-ming-qian** [comment]
Hi,

Yes, the xml is the final one that I am using. You can easily write a script to decode it. Then visualize the segmentation. Sometimes a plane is occluded by other objects (say a floor is occluded by a table), so you will have more than one segment in my annotation for that case. So I visualize my annotation and merge the segment masks if there is a case like that. I am sorry for my late reply.

**Comment by jcliu0428** [comment]
Cool. Thank you for the reply!
